### ISSUE TITLE
LSTM input layer possible?

### ISSUE THREAD

**Issue by RyanHope** [keras-rl/keras-rl#41] opened 2016-11-16 17:43 UTC
Is there a theoretical reason why LSTM couldn't be used as an input layer to a DQN model or is it just a limitation of the implementation? I have been working with an environment where the input could be treated as a sequence of states but up until now I have just been flattening this input. I have a supervised learning keras model with an LSTM input layer that is able to interact with my environment, but when I try using the same model in the DQN agent I get an error about my input dimensions.

**Comment by RyanHope** [comment] 2016-11-20 15:31
As a workaround I used used a flat input and then my first layer before the LSTM was a Reshape layer. Works but seems inefficient.

**Comment by matthiasplappert** [comment] 2016-11-30 12:01
Sorry for the delayed response. Using an LSTM with Q learning is certainly possible but it needs some adoption of the algorithm itself. The problem is that the LSTM needs to be trained on the entire episode from start to finish since otherwise the hidden state of the LSTM will not be correct. Standard DQN, on the other hand, trains the network on random transitions since no state is involved. You can certainly implement DQN with RNNs but you would need to update the memory class in such a way that an entire episode in the form of a sequence is returned.

**Comment by RyanHope** [comment] 2016-12-01 16:16
Thanks.

**Comment by matthiasplappert** [comment] 2016-12-02 14:02
I've started to work on a recurrent implementation of DQN. At this point it does run but it is not yet done nor properly tested. However, if you feel adventurous, you can try it out here: https://github.com/matthiasplappert/keras-rl/tree/recurrent-dqn

**Comment by ViktorM** [comment] 2016-12-03 02:14
Hi Matthias. Do plan ato make RNN implementation also for CDQN and DDPG?

**Comment by matthiasplappert** [comment] 2016-12-03 17:20
I plan to, yes. Still figuring out what the best approach is though and DQN will be the starting point.

**Comment by ViktorM** [comment] 2016-12-04 22:29
Thanks, Matthias! Looking forward for it.

**Comment by ViktorM** [comment] 2017-01-13 19:04
Hi Matthias. Happy New Year! Do you have a chance to continue working on adding RNN to the DDPG?

**Comment by lemonzi** [comment] 2017-01-25 01:05
Hi there, I'm also interested in continuous-action-space recurrent networks. Let me know if you need any help (including tests, code clean-up, etc) in merging the DQN implementation or developing the CDQN/DDPG!

**Comment by matthiasplappert** [comment] 2017-02-02 08:35
I was on an extended vacation until recently and will probably pick up work on this soonish again. However, since I'm only doing this on the side, I cannot really tell you when this will make it into a stable release.

**Comment by ViktorM** [comment] 2017-03-27 15:09
Hi @matthiasplappert , even not release variant will be ok to start experimenting with. Looking forward for it.

**Comment by kfeeeeee** [comment] 2017-04-05 10:57
I would also very much appreciate if the recurrent branch will be fixed and merged into master. As an enhancement double dqn would be of great benefit.

**Comment by RyanHope** [comment] 2017-04-05 13:29
Double dqn is already implemented and the default.

**Comment by kfeeeeee** [comment] 2017-04-05 13:31
What I have meant was double dqn for recurrent dqn.

**Comment by kimardenmiller** [comment] 2017-07-19 01:41
Hi Matthias, impressed to see your quick recurrent-dqn branch and intend to try it out.  My application is time series numeric data currently working in an LSTM regression model, looking to extend that to RL in order to learn a best policy.  Think 10 features presented daily with x days history each, so 3D for the LSTM.  env.action_space.n = 2 possible actions.

Do you have any examples of an env using that kind of data directly, bypassing Gym?

BTW: Grew up a couple hours from you, in Augsburg :-)

**Comment by kimardenmiller** [comment] 2017-08-01 23:14
I have this branch running, but unclear if recurrent demonstrates any advantages.  See my pull request with testing details at: https://github.com/matthiasplappert/keras-rl/pull/125

**Comment by mattdornfeld** [comment] 2018-03-17 22:43
Would using a stateless lstm be a good alternative? That seems like it would be compatible with the random sampling of DQN and DDPG.

**Comment by Bleyddyn** [comment] 2018-04-06 17:55
@matthiasplappert 
> The problem is that the LSTM needs to be trained on the entire episode from start to finish since otherwise the hidden state of the LSTM will not be correct. 

There is a way around that, although it's annoying enough that I'm not sure it's worth doing. You need two models that are identical except that one has stateful set to False and includes a fixed timestep size greater than one in the input shape. The other has stateful set to True and an input shape that has both batchsize and timesteps set to one.

You train (using fit) on the first model with some number of timestep-size contiguous chunks from memory that don't cross episode boundaries, then you load the weights into the second model and test using one environment step at a time.

**Comment by thusinh1969** [comment] 2018-07-08 11:50
An alert: it is extremely SLOW during training with LSTM. I strongly suggest to run a LSTM-VAE to get 2D latent dataset first, and then simply use dense layers to train the DQN / DDPG as you wish. It is hundreds times faster that way.

Cheers.

**Closed** 2019-01-12 16:20 UTC
Labels: wontfix
