### ISSUE TITLE
AttributeError: module 'gym' has no attribute 'undo_logger_setup'

### ISSUE THREAD

**Issue by philipperemy** [keras-rl/keras-rl#277] opened 2018-12-30 23:42 UTC
```
AttributeError: module 'gym' has no attribute 'undo_logger_setup'
```
In pretty much every example.

**Comment by RaphaelMeudec** [comment] 2019-01-05 14:07
Closing this as duplicate of https://github.com/keras-rl/keras-rl/issues/268

**Closed by RaphaelMeudec** 2019-01-05 14:07 UTC

**Comment by philipperemy** [comment] 2019-01-06 00:51
@RaphaelMeudec fair!
