### ISSUE TITLE
Logging bug

### ISSUE THREAD

**Issue by bkj** [keras-rl/keras-rl#12] opened 2016-08-05 04:03 UTC
If you call `Agent.fit` or `Agent.test` repeatedly, the `callbacks` argument gets filled up with (redundant) callbacks. 

To reproduce, change the last line of `examples/dqn_cartpole.py` from

```
dqn.test(env, nb_episodes=5, visualize=True)
```

to

```
print 'first'
dqn.test(env, nb_episodes=5, visualize=False)

print 'second'
dqn.test(env, nb_episodes=5, visualize=False)

print 'third'
dqn.test(env, nb_episodes=5, visualize=False)
```

yielding

```
first
Episode 1: reward: 35.000, steps: 35
Episode 2: reward: 18.000, steps: 18
Episode 3: reward: 17.000, steps: 17
Episode 4: reward: 31.000, steps: 31
Episode 5: reward: 21.000, steps: 21
second
Episode 1: reward: 18.000, steps: 18
Episode 1: reward: 18.000, steps: 18
Episode 2: reward: 13.000, steps: 13
Episode 2: reward: 13.000, steps: 13
Episode 3: reward: 13.000, steps: 13
Episode 3: reward: 13.000, steps: 13
Episode 4: reward: 36.000, steps: 36
Episode 4: reward: 36.000, steps: 36
Episode 5: reward: 13.000, steps: 13
Episode 5: reward: 13.000, steps: 13
third
Episode 1: reward: 33.000, steps: 33
Episode 1: reward: 33.000, steps: 33
Episode 1: reward: 33.000, steps: 33
Episode 2: reward: 18.000, steps: 18
Episode 2: reward: 18.000, steps: 18
Episode 2: reward: 18.000, steps: 18
Episode 3: reward: 27.000, steps: 27
Episode 3: reward: 27.000, steps: 27
Episode 3: reward: 27.000, steps: 27
Episode 4: reward: 19.000, steps: 19
Episode 4: reward: 19.000, steps: 19
Episode 4: reward: 19.000, steps: 19
Episode 5: reward: 25.000, steps: 25
Episode 5: reward: 25.000, steps: 25
Episode 5: reward: 25.000, steps: 25
```

**Comment by matthiasplappert** [comment] 2016-08-05 07:48
Well, that's interesting. The obvious fix is to make a copy of the callbacks list (`callbacks = callbacks[:]`) before adding the loggers in `fit` and `test `. Would you like to open a pull request for this?

**Comment by bkj** [comment] 2016-08-05 13:39
Yeah I will. Out of curiosity though, I was trying to understand how this
was happening though, since it seems like callbacks should take the default
argument value of an empty array. Do you know what's going on there?

**Comment by matthiasplappert** [comment] 2016-08-05 16:01
I don't really know either. It seems like adding to the list somehow modifies the default parameter. It seems like this shouldn't happen in the first place and I don't really have an explanation on what exactly is going on here. I'll leave this issue open for now and will revisit this later to find out what's going on here.

**Comment by SimonRamstedt** [comment] 2016-08-05 16:41
Yes, apparently this is exactly what happens. Therefore http://effbot.org/zone/default-values.htm recommends using `None` over `[]`. But because I didn't know this either I digged a bit deeper into the code and found another related issue:
The Tensorboard logger creates new logging ops everytime its `_set_model` method is called. So if `test` is called multiple times the tensorboard logging will also get redundant because it collects all the logging ops via `tf.merge_all_summaries()`. I'll prepare another small fix for that.

**Comment by SimonRamstedt** [comment] 2016-08-05 17:00
Ok fixed both now for simplicity

**Comment by SimonRamstedt** [comment] 2016-08-05 19:16
I realized just now that the TensorBoard callback class is part of keras and not keras-rl :P
So I guess this particular issue remains for now

**Comment by RyanHope** [comment] 2017-06-20 12:17
A similar issue resides in the FileLogger callback. I removed it to avoid the issue, I will try and add it back later to capture the error message.

**Comment by RaphaelMeudec** [comment] 2018-05-01 14:25
Closing this issue as I can't reproduce the bug anymore. It's probably due to the fact that callbacks default value used to be an empty list instead of None. 
Try out this snippet to see what I'm talking about:
```py
def func_with_default_argument(my_list=[]):
    my_list.append(3)
    print(my_list)
    
print('first call: should return [3]')
func_with_default_argument()

print('second call: we expect [3] but same default argument from first called is used again: [3, 3]')
func_with_default_argument()
```

**Closed by RaphaelMeudec** 2018-05-01 14:25 UTC

**Comment by bsyiem** [comment] 2021-03-18 10:29
This comment may be late but this may provide some insight: https://docs.python-guide.org/writing/gotchas/
