### ISSUE TITLE
Resurrecting Keras-RL

### ISSUE THREAD

**Issue by arsenious** [keras-rl/keras-rl#132] opened 2017-09-18 20:22 UTC
#118 is keras-rl dead  
@ViktorM
I think Keras-RL is one of the best Keras libraries around and is brilliantly structured. Most of the codes I've read are stand-alone i.e. the researcher implements one model and the code is specific to that only. Keras-RL gives structure and is quite extensible.

I understand the author @matthiasplappert  is working for OpenAI (congrats!) and would be quite busy. It'd be nice if we all could get together and maintain this repo. I'd be happy and eager to contribute but to be honest I don't have much experience with maintaining large open source codes.

I'm currently trying to fix the author's DRQN implementation from Dec 2016 to work with current version of Keras-RL/Keras. I've got a decent understanding of how the library has been written. If anyone else has already done it, please let me know, could really use the help.
Thanks

**Comment by matthiasplappert** [comment] 2017-09-19 04:34
I've neglected this library quite badly, unfortunately, due to the fact that I don't have a lot of time for open source work right now. I'd be happy to figure out a better way to maintain this that does not depend solely on me as the bottleneck.

One possibility is to use https://github.com/farizrahman4u/keras-contrib instead, but I feel like keras-rl is probably too big to properly fit into this. Additionally, it does seem like this repository is also not super well maintained, at least according to the fact that the last commit was on August 16th. I'm open to any suggestions to improve this situation.

**Comment by ViktorM** [comment] 2017-09-19 07:06
Hi @matthiasplappert! That issue is quit old, I've created it before you added DDPG with parameter noise implementation to the baselines. So as for me I'm totally fine using baselines instead of keras-rl. Only one piece is missing there that would be nice to have - CDQN implementation. Do you plan to add it?

But in general for most of my research I'm hapoy with PPO and DDPG implementations there.

**Comment by ekerazha** [comment] 2017-09-19 11:08
I know keras-rl is nice because it is based on keras, but maybe we should just switch to TensorForce https://github.com/reinforceio/tensorforce

**Comment by vrishank97** [comment] 2017-09-19 19:33
As @arsenious said this is one of the best Keras RL libraries around. CrowdAI recently launched a competition where they recommend Keras-RL. So we can expect to see a lot more people using it in the coming days.

I'd love to contribute to the repository, but I don't have much experience with open source contributions. Is there some issue or project that I can start with?

**Comment by donjae** [comment] 2017-09-19 19:34
@matthiasplappert I really love your work with keras-rl and really hope that there is a future with this framework. Have you contacted fchollet (keras) and perhaps work on maybe merging the repos? I know it's a bit of a stretch, but I'm pretty sure it's totally not out of the realm of possibility.

But hey, however you choose to maintain this package, I totally respect that decision. Thanks again for your work man

**Comment by matthiasplappert** [comment] 2017-09-20 18:26
I will try to talk to fchollet about this matter but I do not think that Keras-RL will ever become part of the official Keras. Maybe we can figure something out though. Thanks for all the input and the warm words, I really appreciate it!

**Comment by arsenious** [comment] 2017-09-21 05:56
@matthiasplappert  Nice to hear from you!  And thanks for this wonderful library! 
I'm working on memory-augmented Deep RL agents for my thesis and will be happy to contribute all the models I develop using Keras and Keras-RL, to this repo. Beyond that I'd be happy to take some time out and work on fixes and features you'd like for Keras-RL. I'd need some guidance though but I do know a good deal of Deep RL theory as well as Python/Keras Backend coding. 

Like @donjae suggested, you should look at integrating with Keras, especially since Keras-RL is probably the best structured and most comprehensive framework for DRL around, for Keras or otherwise.

As for Tensorforce, it looks nice, but I'd place my bets on Keras. What I love about Keras is that its focus is "layer"-based(not "operation"-based) which leads to very clean and extensible code. I actually like the fact that new layers have to be written following certain conventions. It allows me to share my code for novel layers easily without asking the other teams to change their codes much nor have them move to my preferred DL backend.
And it can seamlessly support multiple backends. Tensorflow is doing great now(especially given that Google is dedicating such a lot of full-time resources on it) ahead but PyTorch (backed by FB) is gaining momentum too. Keras already supports 3 backends, I'm guessing if it becomes necessary, it will support PyTorch too.

Let's try and figure something out. I mean most of us gathered here, are here because we work in a specific field of Deep Learning i.e. Deep Reinforcement Learning, which is a pretty advanced field even within DL. So I'm guessing collectively we'd have the skills to maintain and develop this library.

**Comment by donjae** [comment] 2017-09-21 17:45
@matthiasplappert And please keep us in the loop with what happens! I have no doubt in my mind that @fchollet would be interested in the RL aspect of keras

**Comment by ahundt** [comment] 2017-09-22 04:51
@matthiasplappert I'm a collaborator on keras-contrib, and I think this would be a good fit but I'd want a second opinion, and this would have to be updated to fit with the keras-contrib structure.

**Comment by matthiasplappert** [comment] 2017-09-22 05:07
@ahundt What specifically would have to happen?

**Comment by ahundt** [comment] 2017-09-22 05:42
Actually it looks like the code setup you have would fit pretty well without changes being too crazy. The contents of `rl` might go in `keras_contrib.rl`, and `tests` moved to `tests.keras_contrib.rl` etc for various other small details. Since it is already pep8 I don't think the code formatting would be too big a jump. 

Since this is so much code compared to keras-contrib, would you mind either posting on slack [https://kerasteam.slack.com](https://www.google.com/url?q=https%3A%2F%2Fkerasteam.slack.com&sa=D&sntz=1&usg=AFQjCNF-Oi-VUC8wRcYECHKXV2WIkmO_tw) in the keras-dev channel or send an email to keras-users@googlegroups.com to see what others think?

**Comment by ahundt** [comment] 2017-10-01 20:55
@matthiasplappert is there anything you need w.r.t. keras-contrib?

**Comment by martindinov** [comment] 2017-10-04 12:30
I've used Keras-RL (especially DQNs) somewhat as part of my PhD research and have separately used Keras on some occasions. I'm happy to help in some ways too if @matthiasplappert wants to leave further development of it into the hands of a community which likes and is using Keras-RL.

**Comment by matthiasplappert** [comment] 2017-10-12 13:01
I'm still not sure if contrib is the right place for Keras-RL since it is a relatively big chunk of code and contrib seems to contain mostly different types of layers etc. I'd be happy to discuss with the Keras team, but I can't join the Slack channel. If someone could invite me, that'd be great (my email is matthiasplappert@me.com).

Besides this, I think I can do at least a better job of merging PRs. I won't have enough time to develop any real new features for the most part, mostly because I do not use Keras-RL for my own research anymore. However, if people wish to contribute, I'll at least try to be available to work with them on their PRs.

**Comment by whatever1983** [comment] 2017-11-30 06:48
@fchollet, @matthiasplappert, @jjallaire
Merging this with fchollet/keras is a must.  That way it will always be kept up to date with the latest keras, and when RStudio/keras's reticulate interface into python's keras is done, even R people can do RL in RStudio with multigpu.  That would be awesome.

**Comment by fchollet** [comment] 2017-11-30 19:09
We could consider merging specific broadly-useful features. Would have you
a short list of what's currently missing in Keras for people who do RL?

**Comment by matthiasplappert** [comment] 2017-12-04 11:15
Keras-RL is mostly missing recent advances like PPO (https://arxiv.org/abs/1707.06347) and A3C (https://arxiv.org/pdf/1602.01783.pdf). There's also a recent trend of distributing training across multiple cores or machine, and Keras-RL was not designed for this use case. Besides this, Keras-RL struggles to keep up with changes in Keras since I don't use it for my own research anymore. Probably most importantly, Keras-RL desperately needs better documentation and guides to help new users get started.

I'm happy to help in the transition process as much as possible. It would be great to somehow transition maintenance to the Keras community, which seems pretty active. It feels like a significant part of the problem is also that I'm the major bottleneck when it comes to contributions since every PR has to be approved by me.

**Comment by rbauld** [comment] 2017-12-05 17:04
IMO I really like this package. It was a great way to jump into reinforcement learning without spending too much time on implementation. I could start solving problems/playing with models and features basically right away. Currently I have built a system to do day trading, seems to work decently well to! (at lest in testing!)

Machine/deep learning is more of a hobby of mine currently, but I wouldn't mind contributing what I can.

**Comment by ahundt** [comment] 2017-12-06 21:23
@matthiasplappert don't forget rainbow in the list of missing implementations https://arxiv.org/abs/1710.02298

**Comment by chairbender** [comment] 2018-01-19 20:25
I just discovered tensorforce. It seems like a better alternative to this, considering this is dead. Recommend checking it out if you are looking for something.

**Comment by lemonteaa** [comment] 2018-01-30 15:12
@matthiasplappert First off, applause for all the efforts you've put into this nice repository. If you think this is too big to fit into contrib, then how about marking it as a "sister project" / "subproject" of keras? (Just a quick thought)

**Comment by RaphaelMeudec** [comment] 2018-03-26 10:45
Hi everyone! More maintainers have joined to help keeping this repo alive. If you have some ideas on what's a priority to you, I would be glad to have some feedbacks on what's a must-do over the next weeks!

**Closed** 2018-04-02 07:21 UTC
